//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSEncuestaConglomerado.Models.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuadrantes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cuadrantes()
        {
            this.Encuesta = new HashSet<Encuesta>();
        }
    
        public int cua_id { get; set; }
        public string cua_nombre { get; set; }
        public Nullable<int> loc_id { get; set; }
        public Nullable<int> upz_id { get; set; }
        public string cua_cod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Encuesta> Encuesta { get; set; }
    }
}
