//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSEncuestaConglomerado.Models.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosRecepcion
    {
        public int Id { get; set; }
        public int Ideyr_dyr { get; set; }
        public int Idrvp_dyr { get; set; }
        public string dato_dyr { get; set; }
        public string Texto_dyr { get; set; }
        public Nullable<int> Codigouym_dyr { get; set; }
        public int Codigousu_dyr { get; set; }
        public System.DateTime Fecha_dyr { get; set; }
        public Nullable<int> Periodoeyr_dyr { get; set; }
    }
}
