//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSEncuestaConglomerado.Models.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Encuesta
    {
        public long enc_id { get; set; }
        public System.DateTime enc_fecha { get; set; }
        public int loc_id { get; set; }
        public int upz_id { get; set; }
        public int bar_id { get; set; }
        public int cua_id { get; set; }
        public string enc_muestreadopor { get; set; }
        public string enc_nombreencuestado { get; set; }
        public int tpd_id { get; set; }
        public string enc_numerodocumento { get; set; }
        public int enc_edad { get; set; }
        public string enc_genero { get; set; }
        public string enc_dirresidencia { get; set; }
        public string enc_numcelular { get; set; }
        public string enc_aseguramiento { get; set; }
        public string enc_nombreEAPB { get; set; }
        public string enc_ocupacion { get; set; }
        public int enc_cuantaspersonashabitan { get; set; }
        public int enc_cuantaspersonasmayores60 { get; set; }
        public int enc_cuantascondicionescronicas { get; set; }
        public int enc_cuantashabitacionescuentaresidencia { get; set; }
        public Nullable<bool> enc_hapresentadosintomas_fiebre { get; set; }
        public Nullable<bool> enc_hapresentadosintomas_tos { get; set; }
        public Nullable<bool> enc_hapresentadosintomas_dolorgarganta { get; set; }
        public Nullable<bool> enc_hapresentadosintomas_fatigadebilidad { get; set; }
        public Nullable<bool> enc_hapresentadosintomas_ahogofaltaaire { get; set; }
        public Nullable<bool> enc_hapresentadosintomas_ninguno { get; set; }
        public string enc_comoconsideracumplimientocuarentena { get; set; }
        public string enc_contactopersonas24horas { get; set; }
        public string enc_dondedesplazoustedomiembrofamilia { get; set; }
        public Nullable<bool> enc_motivosalirdecasa_noaplica { get; set; }
        public Nullable<bool> enc_motivosalirdecasa_atrabajar { get; set; }
        public Nullable<bool> enc_motivosalirdecasa_compraralimento { get; set; }
        public Nullable<bool> enc_motivosalirdecasa_ahacerdeporte { get; set; }
        public Nullable<bool> enc_motivosalirdecasa_acitamedica { get; set; }
        public Nullable<bool> enc_motivosalirdecasa_sacarmascota { get; set; }
        public Nullable<bool> enc_motivosalirdecasa_diligenciabancaria { get; set; }
        public Nullable<bool> enc_motivosalirdecasa_socializar { get; set; }
        public Nullable<bool> enc_motivosalirdecasa_otro { get; set; }
        public string enc_otromotivosalirdecasa { get; set; }
        public Nullable<bool> enc_mediostransporteutilizo_noaplica { get; set; }
        public Nullable<bool> enc_mediostransporteutilizo_transmilenio { get; set; }
        public Nullable<bool> enc_mediostransporteutilizo_sitp { get; set; }
        public Nullable<bool> enc_mediostransporteutilizo_moto { get; set; }
        public Nullable<bool> enc_mediostransporteutilizo_bicicleta { get; set; }
        public Nullable<bool> enc_mediostransporteutilizo_taxi { get; set; }
        public Nullable<bool> enc_mediostransporteutilizo_carro { get; set; }
        public Nullable<bool> enc_mediostransporteutilizo_apie { get; set; }
        public Nullable<bool> enc_mediostransporteutilizo_otro { get; set; }
        public int usu_id { get; set; }
        public System.DateTime enc_datetimecreated { get; set; }
        public Nullable<int> cpm_id { get; set; }
        public Nullable<int> sub_id { get; set; }
        public Nullable<int> enc_usu_modificacion { get; set; }
        public Nullable<System.DateTime> enc_datetimeupdated { get; set; }
        public string enc_estado { get; set; }
    
        public virtual Barrios Barrios { get; set; }
        public virtual CriterioPriorizacionMuestra CriterioPriorizacionMuestra { get; set; }
        public virtual Cuadrantes Cuadrantes { get; set; }
        public virtual Localidades Localidades { get; set; }
        public virtual Subred Subred { get; set; }
        public virtual TipoDocumento TipoDocumento { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
