//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSEncuestaConglomerado.Models.EDMX
{
    using System;
    
    public partial class SP_LIST_ENCUESTAS_Result2
    {
        public long enc_id { get; set; }
        public string enc_fecha { get; set; }
        public string loc_nombre { get; set; }
        public string upz_nombre { get; set; }
        public string bar_nombre { get; set; }
        public string cua_nombre { get; set; }
        public string enc_muestreadopor { get; set; }
        public string cpm_nombre { get; set; }
        public string enc_nombreencuestado { get; set; }
        public string tpd_nombre { get; set; }
        public string enc_numerodocumento { get; set; }
        public int enc_edad { get; set; }
        public string enc_genero { get; set; }
        public string enc_dirresidencia { get; set; }
        public string enc_numcelular { get; set; }
        public string enc_aseguramiento { get; set; }
        public string enc_nombreEAPB { get; set; }
        public string enc_ocupacion { get; set; }
        public int enc_cuantaspersonashabitan { get; set; }
        public int enc_cuantaspersonasmayores60 { get; set; }
        public int enc_cuantascondicionescronicas { get; set; }
        public int enc_cuantashabitacionescuentaresidencia { get; set; }
        public Nullable<bool> enc_hapresentadosintomas_fiebre { get; set; }
        public Nullable<bool> enc_hapresentadosintomas_tos { get; set; }
        public Nullable<bool> enc_hapresentadosintomas_dolorgarganta { get; set; }
        public Nullable<bool> enc_hapresentadosintomas_fatigadebilidad { get; set; }
        public Nullable<bool> enc_hapresentadosintomas_ahogofaltaaire { get; set; }
        public Nullable<bool> enc_hapresentadosintomas_ninguno { get; set; }
        public string enc_comoconsideracumplimientocuarentena { get; set; }
        public string enc_contactopersonas24horas { get; set; }
        public string enc_dondedesplazoustedomiembrofamilia { get; set; }
        public Nullable<bool> enc_motivosalirdecasa_noaplica { get; set; }
        public Nullable<bool> enc_motivosalirdecasa_atrabajar { get; set; }
        public Nullable<bool> enc_motivosalirdecasa_compraralimento { get; set; }
        public Nullable<bool> enc_motivosalirdecasa_ahacerdeporte { get; set; }
        public Nullable<bool> enc_motivosalirdecasa_acitamedica { get; set; }
        public Nullable<bool> enc_motivosalirdecasa_sacarmascota { get; set; }
        public Nullable<bool> enc_motivosalirdecasa_diligenciabancaria { get; set; }
        public Nullable<bool> enc_motivosalirdecasa_socializar { get; set; }
        public Nullable<bool> enc_motivosalirdecasa_otro { get; set; }
        public string enc_otromotivosalirdecasa { get; set; }
        public Nullable<bool> enc_mediostransporteutilizo_noaplica { get; set; }
        public Nullable<bool> enc_mediostransporteutilizo_transmilenio { get; set; }
        public Nullable<bool> enc_mediostransporteutilizo_sitp { get; set; }
        public Nullable<bool> enc_mediostransporteutilizo_moto { get; set; }
        public Nullable<bool> enc_mediostransporteutilizo_bicicleta { get; set; }
        public Nullable<bool> enc_mediostransporteutilizo_taxi { get; set; }
        public Nullable<bool> enc_mediostransporteutilizo_carro { get; set; }
        public Nullable<bool> enc_mediostransporteutilizo_apie { get; set; }
        public Nullable<bool> enc_mediostransporteutilizo_otro { get; set; }
        public string sub_nombre { get; set; }
        public string usu_nombre { get; set; }
        public System.DateTime enc_datetimecreated { get; set; }
        public string usu_nombre_modificacion { get; set; }
        public Nullable<System.DateTime> enc_datetimeupdated { get; set; }
        public string enc_estadoembarazo { get; set; }
        public string enc_etnia { get; set; }
        public string enc_condiciondiscapacidad { get; set; }
        public Nullable<bool> enc_presentaenfermedad_hipertension { get; set; }
        public Nullable<bool> enc_presentaenfermedad_diabetesmellitus { get; set; }
        public Nullable<bool> enc_presentaenfermedad_obesidad { get; set; }
        public Nullable<bool> enc_presentaenfermedad_epoc { get; set; }
        public Nullable<bool> enc_presentaenfermedad_asma { get; set; }
        public Nullable<bool> enc_presentaenfermedad_otro { get; set; }
        public string enc_presentaenfermedad_otrocuales { get; set; }
        public Nullable<bool> enc_hapresentadosintomas_diarrea { get; set; }
        public Nullable<bool> enc_hapresentadosintomas_perdidaolfato { get; set; }
        public string enc_contactopersonascuantas { get; set; }
        public string enc_dispuestoaislamiento { get; set; }
        public string enc_vacunadocovid { get; set; }
        public string enc_accedetomamuestra { get; set; }
        public Nullable<bool> enc_convivepresentadosintomas_fiebre { get; set; }
        public Nullable<bool> enc_convivepresentadosintomas_tos { get; set; }
        public Nullable<bool> enc_convivepresentadosintomas_dolorgarganta { get; set; }
        public Nullable<bool> enc_convivepresentadosintomas_fatigadebilidad { get; set; }
        public Nullable<bool> enc_convivepresentadosintomas_ahogofaltaaire { get; set; }
        public Nullable<bool> enc_convivepresentadosintomas_ninguno { get; set; }
        public Nullable<bool> enc_convivehapresentadosintomas_diarrea { get; set; }
        public Nullable<bool> enc_convivehapresentadosintomas_perdidaolfato { get; set; }
        public Nullable<bool> enc_presentaenfermedad_ninguno { get; set; }
        public string enc_compartehabitacion { get; set; }
        public Nullable<bool> enc_hapresentadosintomas_dolorestomago { get; set; }
        public Nullable<bool> enc_convivepresentadosintomas_dolorestomago { get; set; }
        public string enc_frecuenciadesplazamiento { get; set; }
        public string enc_esquemavacunacioncompleto { get; set; }
    }
}
