//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSEncuestaConglomerado.Models.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Upz
    {
        public int upz_id { get; set; }
        public string upz_nombre { get; set; }
        public int loc_id { get; set; }
        public int upz_codigo { get; set; }
        public int loc_codigo { get; set; }
        public string upz_estado { get; set; }
    }
}
