//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSEncuestaConglomerado.Models.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.Encuesta = new HashSet<Encuesta>();
        }
    
        public int usu_id { get; set; }
        public string usu_nombre { get; set; }
        public string usu_login { get; set; }
        public string usu_password { get; set; }
        public string usu_estado { get; set; }
        public int rol_id { get; set; }
        public bool usu_req_clave { get; set; }
        public Nullable<System.DateTime> usu_datetimecreated { get; set; }
        public Nullable<int> sub_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Encuesta> Encuesta { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
