export class Encuesta {
    constructor(
        public enc_id: number,
        public enc_fecha: Date,
        public enc_dia: string,
        public enc_mes: string,
        public enc_ano: string,
        public loc_id: number,
        public upz_id: number,
        public bar_id: number,
        public cua_id: number,
        public enc_muestreadopor: string,
        public cpm_id: number,
        public enc_nombreencuestado: string,
        public tpd_id: number,
        public enc_numerodocumento: string,
        public enc_edad: number,
        public enc_genero: string,
        public enc_dirresidencia: string,
        public enc_numcelular: string,
        public enc_aseguramiento: string,
        public enc_nombreEAPB: string,
        public enc_ocupacion: string,
        public enc_cuantaspersonashabitan: number,
        public enc_cuantaspersonasmayores60: number,
        public enc_cuantascondicionescronicas: number,
        public enc_cuantashabitacionescuentaresidencia: number,
        public enc_hapresentadosintomas_fiebre: boolean,
        public enc_hapresentadosintomas_tos: boolean,
        public enc_hapresentadosintomas_dolorgarganta: boolean,
        public enc_hapresentadosintomas_fatigadebilidad: boolean,
        public enc_hapresentadosintomas_ahogofaltaaire: boolean,
        public enc_hapresentadosintomas_ninguno: boolean,
        public enc_comoconsideracumplimientocuarentena: string,
        public enc_contactopersonas24horas: string,
        public enc_dondedesplazoustedomiembrofamilia: string,
        public enc_motivosalirdecasa_noaplica: boolean,
        public enc_motivosalirdecasa_atrabajar: boolean,
        public enc_motivosalirdecasa_compraralimento: boolean,
        public enc_motivosalirdecasa_ahacerdeporte: boolean,
        public enc_motivosalirdecasa_acitamedica: boolean,
        public enc_motivosalirdecasa_sacarmascota: boolean,
        public enc_motivosalirdecasa_diligenciabancaria: boolean,
        public enc_motivosalirdecasa_socializar: boolean,
        public enc_motivosalirdecasa_otro: boolean,
        public enc_otromotivosalirdecasa: string,
        public enc_mediostransporteutilizo_noaplica: boolean,
        public enc_mediostransporteutilizo_transmilenio: boolean,
        public enc_mediostransporteutilizo_sitp: boolean,
        public enc_mediostransporteutilizo_moto: boolean,
        public enc_mediostransporteutilizo_bicicleta: boolean,
        public enc_mediostransporteutilizo_taxi: boolean,
        public enc_mediostransporteutilizo_carro: boolean,
        public enc_mediostransporteutilizo_apie: boolean,
        public enc_mediostransporteutilizo_otro: boolean,
        public sub_id: number,
        public usu_id : number


    ) { }
}


export class ListaEncuesta {
    constructor(
        public enc_id: number,
        public enc_fecha: string,
        public enc_dia: string,
        public enc_mes: string,
        public enc_ano: string,
        public loc_nombre: string,
        public upz_nombre: string,
        public bar_nombre: string,
        public cua_nombre: string,
        public enc_muestreadopor: string,
        public cpm_nombre: string,
        public enc_nombreencuestado: string,
        public tpd_nombre: string,
        public enc_numerodocumento: string,
        public enc_edad: string,
        public enc_genero: string,
        public enc_dirresidencia: string,
        public enc_numcelular: string,
        public enc_aseguramiento: string,
        public enc_nombreEAPB: string,
        public enc_ocupacion: string,
        public enc_cuantaspersonashabitan: number,
        public enc_cuantaspersonasmayores60: number,
        public enc_cuantascondicionescronicas: number,
        public enc_cuantashabitacionescuentaresidencia: number,
        public enc_hapresentadosintomas_fiebre: boolean,
        public enc_hapresentadosintomas_tos: boolean,
        public enc_hapresentadosintomas_dolorgarganta: boolean,
        public enc_hapresentadosintomas_fatigadebilidad: boolean,
        public enc_hapresentadosintomas_ahogofaltaaire: boolean,
        public enc_hapresentadosintomas_ninguno: boolean,
        public enc_comoconsideracumplimientocuarentena: string,
        public enc_contactopersonas24horas: string,
        public enc_dondedesplazoustedomiembrofamilia: string,
        public enc_motivosalirdecasa_noaplica: boolean,
        public enc_motivosalirdecasa_atrabajar: boolean,
        public enc_motivosalirdecasa_compraralimento: boolean,
        public enc_motivosalirdecasa_ahacerdeporte: boolean,
        public enc_motivosalirdecasa_acitamedica: boolean,
        public enc_motivosalirdecasa_sacarmascota: boolean,
        public enc_motivosalirdecasa_diligenciabancaria: boolean,
        public enc_motivosalirdecasa_socializar: boolean,
        public enc_motivosalirdecasa_otro: boolean,
        public enc_otromotivosalirdecasa: string,
        public enc_mediostransporteutilizo_noaplica: boolean,
        public enc_mediostransporteutilizo_transmilenio: boolean,
        public enc_mediostransporteutilizo_sitp: boolean,
        public enc_mediostransporteutilizo_moto: boolean,
        public enc_mediostransporteutilizo_bicicleta: boolean,
        public enc_mediostransporteutilizo_taxi: boolean,
        public enc_mediostransporteutilizo_carro: boolean,
        public enc_mediostransporteutilizo_apie: boolean,
        public enc_mediostransporteutilizo_otro: boolean,
        public sub_nombre: string,
        public usu_nombre : string,
        public usu_nombre_modificacion: string,
        public enc_datetimeupdate : Date
    ) { }
}

export class EdicionEncuesta {
  constructor(
      public enc_id: number,
      public editar: boolean,
     
  ) { }
}